# File: cloudbuild.yaml
steps:
- name: 'gcr.io/idfy-299017/git'
  args: ['clone', 'https://github.com/ammut891/cloud-build.git']
options:
  logging: CLOUD_LOGGING_ONLY
images: ['gcr.io/idfy-299017/git']