steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --plaintext-file=secrets.json
  - --location=global
  - --keyring=packer
  - --key=key
- name: 'gcr.io/$PROJECT_ID/packer'
  args:
    - build
    - -var
    - project_id=$PROJECT_ID
    - 'packer/docker.json'
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1800s
tags: ['packer-gce-goss']